### PR TITLE
fix build for non-go18

### LINKED ISSUE #68: Anko no longer supports < 1.8
This commit: https://github.com/mattn/anko/commit/9e581b751c2e001e4035bfcff3d9731fc430b7bc broke support for versions of Go less than 1.8. Typically, projects try to support the current version, plus the previous version. 

This ticket is really to confirm that you meant to stop supporting <= 1.7. Please confirm.

### PR DESCRIPTION
**Pull request by mattn**
fixes #68

### CODE REVIEW

**Comment by markbates** [comment]
Awesome! Thanks.

File: builtins/sort/sort.go [hunk 1]
```diff
@@ -44,19 +43,6 @@ func Import(env *vm.Env) *vm.Env {
...
 		return arr
 	})
-	m.Define("Strings", func(arr interface{}) interface{} {
-		if sarr, ok := arr.([]string); ok {
-			s.Strings(sarr)
-		} else {
-			s.Sort(ss(arr.([]interface{})))
-		}
-		return arr
-	})
```
Comment (mattn) [inline builtins/sort/sort.go]: Ah, Strings was gone. :-(
